### PR TITLE
Full Naming Control and minor changes

### PR DESCRIPTION
**Pull request by forddasav**
dave,

Just some quick changes. Think I did the pull request right. Only a few files were changed (index.html, smasherbot.js and script.js from backup folder.)

New Features:
Complete Naming Control
More names for random names
-minor css changes
-other minor changes
thanks,
ford

### CODE REVIEW

**Comment by DaveDuck321** [comment]
Before I merge this, what does "Complete naming control" mean specifically

**Comment by DaveDuck321** [comment]
I have not merged this directly due to a mismatch in versions but I have manually re-implemented (most) of your changes

**Comment by forddasav** [comment]
Whoops my bad. Where the version numbers the same?

**Comment by DaveDuck321** [comment]
The version I uploaded here was the stable version, the version you had been working on was the beta, no need to worry though I have updated this to the beta version and I went through you changes, implementing them in the correct version.

**Pull request closed without merging**
